# Required
appName=You Tube
websiteUrl=https://youtube.com
iconUrl=https://raw.githubusercontent.com/github/explore/main/topics/android/android.png

# Optional
applicationId=
versionCode=1
versionName=1.0.0
minSdk=21
allowCleartext=false
iconBackgroundColor=#FFFFFF
userAgentSuffix=
